name: "Housekeeping: Limpeza de Branches"

on:
  schedule:
    # Roda toda segunda-feira às 03:00
    - cron: '0 3 * * 1'
  workflow_dispatch: # Permite que você clique no botão "Run" para testar

permissions:
  contents: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # USANDO A ACTION OFICIAL DO GITHUB (actions/stale)
      - name: Limpeza de branches inativas
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Configurações para deletar branches sem mexer em Issues/PRs
          days-before-stale: 30
          days-before-branch-delete: 0
          exempt-branch-mats: "main,master,develop"
          stale-issue-message: "none"
          stale-pr-message: "none"